name = "blog-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "blog-api-production"

[env.staging]
name = "blog-api-staging"

[[d1_databases]]
binding = "DB"
database_name = "blog-database"
database_id = "your-database-id"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "blog-media"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

[ai]
binding = "AI"

[vars]
JWT_SECRET = "your-jwt-secret-key"
ADMIN_API_KEY = "your-admin-api-key"

# For local development, create a .dev.vars file with:
# JWT_SECRET=your-local-jwt-secret
# ADMIN_API_KEY=your-local-admin-api-key
